/**
 * Javascripts specific for this theme
 *
 *
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
 
jQuery(document).ready(function($) {
    var height = $('#navigation_menu').height();
	var margin = 0;

	if( $(".admin-bar") ) {
		margin = $("#wpadminbar").height();
	}

	$('#navigation_menu').css("top", margin + "px");
	$("#header_section").css("margin-top", height + "px");
});