/**
 * Javascripts specific for this theme
 *
 *
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

/**
 * Makes header clear the static menu bar
 */
jQuery(document).ready(function($) {
    var height = $('#navigation_menu').height();

	// Remove a small discrepancy with the height calculation
	height = height - 5;

	$("#header_section").css("margin-top", height + "px");
});